Sprint 3
andreyatx/middle.messenger.praktikum.yandex pull request #5
Opened 2022-11-02 22:39 UTC by andreyatx

Привет, добавил роутинг, авторизацию и страницу чатов. 
Не работает отправка сообщений, работаю над этим.
Изменение данных/пароля, добавление/удаление чатов ещё не сделал.
Понимаю, что много всего надо править, буду работать над замечаниями.

2022-11-03 14:15 UTC, agadoev requested changes
Привет, @andreyatx 
Спасибо за работу
В целом все ок, но я отметил места, над которыми еще стоит подумать
Давай доведем работу до конца и двинемся дальше

2022-11-03 14:15 UTC, agadoev commented on .eslintignore
> +/dist
1) интересно, в чем существенное отличие build от dist
2) я бы добавил сюда еще .parcel-cache

2022-11-03 14:15 UTC, agadoev commented on package.json
> +		"nanoid": "^4.0.0",
эта зависимость должна быть в dependencies, потому что код этой библиотеки будет отправляться на клиент и исполняться в браузере

2022-11-03 14:15 UTC, agadoev commented on package.json
> +		"stylelint-config-standard": "^28.0.0"
а вот эта зависимость скорее всего должна находиться в ```devDependencies```

2022-11-03 14:15 UTC, agadoev commented on src/components/Chat/index.ts
> +  selectedChat: ChatInfo;
В названии этих свойств используется snake_case и camelCase. Надо оставить что-то одно, чтобы стиль кода был единым. Если не следить за стилем кода, то код быстро станет трудно поддерживать (касается всего проекта)

2022-11-03 14:15 UTC, agadoev commented on src/components/DataField/index.ts
> +  classes?: string;
Что, если потребуется задать более одного класса? Тут лучше подойдет ```string[]```. С массивом строк проще работать, чем со строкой, потому что не придется парсить строку

2022-11-03 14:15 UTC, agadoev commented on src/utils/Validation.ts
> +}
Подумай над тем, чтобы использовать union вместо enum'a. Union не транспилируется в объект, как enum, и на не нужно дублировать код (сейчас для каждого элемента перечисления дублируется строка). Подробнее можно почитать [тут](https://stackoverflow.com/questions/40275832/typescript-has-unions-so-are-enums-redundant)

2022-11-03 14:15 UTC, agadoev commented on src/utils/Validation.ts
> +      // }
Закомментированный код лучше не держать в репозитории. Он загрязняет кодовую базу и отвлекает внимание.

2022-11-03 14:15 UTC, agadoev commented on src/utils/Store.ts
> +  private state: any = {
Надо описать тип для state

2022-11-03 14:15 UTC, agadoev commented on src/pages/SignUp/index.ts
> +  };
здесь точно нужно передавать дочерние компоненты в качестве пропсов? Обычно дочерние компоненты указываются в шаблоне

2022-11-03 14:15 UTC, agadoev commented on src/controllers/AuthController.ts
> +    this.api = API;
Лучше написать вот так
```suggestion
    this.api = new API();
```

или что-то типа того. Чтобы класс сам контролировал создание своих зависимостей

2022-11-03 14:15 UTC, agadoev commented on src/controllers/ChatsController.ts
> +    this.fetchChats();
Нужно перехватить ошибку и вывести пользователю сообщение о ней

2022-11-06 13:56 UTC, andreyatx commented on src/controllers/AuthController.ts
> +    this.api = API;
Не уверен, что это правильно. Но в AuthAPI написано: export default new AuthAPI();

2022-11-06 14:32 UTC, andreyatx commented on src/components/DataField/index.ts
> +  classes?: string;
Попробую сделать. В Block.ts _addClass вроде справляется со строкой

2022-11-06 16:47 UTC, andreyatx commented
Привет. Добавил возможность отправлять сообщения, добавлять/удалять чаты.
Вроде все исправил по ревью.

2022-11-07 00:13 UTC, agadoev commented on src/controllers/AuthController.ts
> +    this.api = API;
Я понимаю, но сейчас класс ```AuthController``` использует объект, который создается где-то вовне. Если этот объект. Если этот объект удалить из памяти, то и работа ```AuthController``` будет нарушена. 
Я так понимаю, что ты хотел сделать что-то типа синглтона, но сейчас это не синглтон. Сейчас просто экспортируется один инстанс объекта. Синглтон реализуется через статический метод и при любом создании объекта будет будет возвращаться один и тот же инстанс. Про синглтон можешь почитать [тут](https://refactoring.guru/design-patterns/singleton/typescript/example)

2022-11-07 00:14 UTC, agadoev approved these changes
Привет, @andreyatx 
все ок, про зависимость от API постарался объяснить)
Работа принимается, удачи в следующем спринте :)

2022-11-08 15:56 UTC, merged